application: purple-number
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /script
  static_dir: script

- url: /svg
  static_dir: svg

- url: /.*
  script: helloworld.app
  login: required

libraries:
- name: jinja2
  version: latest
