application: purple-number
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  mime_type: text/css; charset=utf-8

- url: /script
  static_dir: script
  mime_type: application/javascript

- url: /svg
  static_dir: svg
  mime_type: image/svg+xml

- url: /.*
  script: helloworld.app
  login: required

libraries:
- name: jinja2
  version: latest
